account/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.


from account import views
from django.urls import path, re_path
from .views import (
    ArticleView,
    LogoutView,
    ArticleCreate,
    ArticleUpdate,
    ArticleDelete,
    Profile,
    PasswordChange,
    PasswordChangeDone,
    Register,
)





app_name = 'account'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.SingUpView, name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
    path(
        "password_change/", PasswordChange.as_view(), name="password_change"
    ),
    path(
        "password_change/done/",
        PasswordChangeDone.as_view(),
        name="password_change_done",
    ),
    path(
        'activate/<slug:uidb64>/<slug:token>/',
        views.activate,
        name='activate'
    )

]

urlpatterns +=[
    path('', ArticleView.as_view(), name='admin-home'),
    path('article/create', ArticleCreate.as_view(), name='create'),
    path('article/update/<int:pk>', ArticleUpdate.as_view(), name='update'),
    path('article/create/<int:pk>', ArticleDelete.as_view(), name='delete'),
    path('profile/', Profile.as_view(), name='profile'),

]

blog/urls.py
from django.urls import path
from .views import (
    ArticleList,
    CategoryList,
    ArticleDetail,
    AuthorList,
    ArticlePreview,
    ContactFormView,
)
from . import views

app_name = 'blog'
urlpatterns = [
    path('', ArticleList.as_view(), name='home'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('page/<int:page>', ArticleList.as_view(), name='home'),
    path('article/<str:slug>', ArticleDetail.as_view(), name='article-detail'),
    path('preview/<int:pk>', ArticlePreview.as_view(), name='preview'),
    path('category/<str:slug>', CategoryList.as_view(), name='category'),
    path('category/<str:slug>/page/<int:page>', CategoryList.as_view(), name='category'),
    path('author/<str:username>', AuthorList.as_view(), name='author'),
    path('author/<str:username>/page/<int:page>', AuthorList.as_view(), name='author'),

    path('search/', views.search_feature, name='search-view'),

]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoProject1 import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('account/', include('django.contrib.auth.urls')),

    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('payment/', include('payment.urls')),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sit_blog_me/urls.py
from django.contrib import admin
from django.urls import path, include
from sit_blog_me import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    path('account/', include('django.contrib.auth.urls')),

    path('account/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('payment/', include('payment.urls')),

    path('ratings/', include('star_ratings.urls', namespace='ratings')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from django_ckeditor_5.fields import CKEditor5Field
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment


#my manager

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آیپی')

class Category(models.Model):
    parent = models.ForeignKey('self',default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name = 'عنوان دسته بندی')
    slug = models.SlugField(max_length=100,unique=True,allow_unicode=True, verbose_name = 'آدرس دسته بندی')
    status = models.BooleanField(default= True,verbose_name = ' آیا نمایش داده شود؟ ')
    position = models.IntegerField(verbose_name = 'پوزیشن')
    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id','position']

    def __str__(self):
        return self.title

    objects = CategoryManager()

    def save(self, *args, **kwargs):
        if not self.status:
            for article in self.articles.published():
                article.status = 'd'
                article.save()
        super(Category, self).save(*args, **kwargs)

class Article(models.Model):
    STATUS_CHOICES = (
       ('p', 'منتشر شده'),          # publish
       ('d', 'پیش نویس'),           # draft
       ('i', 'در حال بررسی'),       # investigation
       ('b', 'برگشت داده شده'),     # back
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name="نویسنده")
    title = models.CharField(max_length=200, unique=True,verbose_name = 'عنوان پست')
    slug = models.SlugField(max_length=100,unique=True,allow_unicode=True, verbose_name = 'آدرس پست')
    category = models.ManyToManyField(Category, verbose_name = 'دسته بندی', related_name='articles')
    excerpt = models.TextField(max_length=100, verbose_name = ' چکیده مطالب پست')
    description =CKEditor5Field('متن پست')
    photo = models.ImageField(upload_to='media', verbose_name = 'آدرس عکس پست')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name ='وضعیت انتشار ')
    is_special = models.BooleanField(default=False, verbose_name=' پست ویژه ')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, blank=True, related_name="hits", verbose_name='بازدید ها')

    class Meta:
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'
        ordering = ['-publish']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("account:admin-home")

    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "زمان انتشار"


    def photo_tag(self):
        return format_html("<img width=100 height=75 style='border-radius: 5px;' src='{}' />".format(self.photo.url))
    photo_tag.short_description = "عکس پست"

    def category_to_str(self):
        return ", ".join([category.title for category in self.category.active()])
    category_to_str.short_description = 'دسته بندی'

    objects = ArticleManager()
# Create your models here.

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView
from account.models import User
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.mixins import AuthorAccessMixin
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from .form import ContactForm
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render

#
class MyPaginator(Paginator):
    def validate_number(self, number):
        try:
            return super().validate_number(number)
        except EmptyPage:
            if int(number) > 1:
                # return the last page
                return self.num_pages
            elif int(number) < 1:
                # return the first page
                return 1
            else:
                raise


class ArticleList(ListView):
    # model = Article
    template_name = "blog/home.html"
    # context_object_name = 'articles'
    queryset = Article.objects.published()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page', 1)
        users = Article.objects.published()
        paginator = self.paginator_class(users, self.paginate_by)

        users = paginator.page(page)

        context['users'] = users
        return context


class ArticleDetail(DetailView):
    template_name = "blog/article_detail.html"
    def get_object(self):
        slug = self.kwargs.get("slug")
        article = get_object_or_404(Article.objects.published(), slug=slug)

        ip_address = self.request.user.ip_address

        if ip_address not in article.hits.all():
            article.hits.add(ip_address)


        return article

class ArticlePreview(AuthorAccessMixin, DetailView):
    def get_object(self):
        pk = self.kwargs.get("pk")
        return get_object_or_404(Article, pk=pk)


class CategoryList(ListView):
    paginate_by = 3
    template_name = "blog/category_list.html"
    def get_queryset(self):
        global category
        slug = self.kwargs.get("slug")
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        slug = self.kwargs.get("slug")
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context

class AuthorList(ListView):
    paginate_by = 3
    template_name = "blog/author_list.html"
    def get_queryset(self):
        global author
        username = self.kwargs.get("username")
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context


@csrf_exempt
def search_feature(request):
    # Check if the request is a post request.
    if request.method == 'POST':
        # Retrieve the search query entered by the user
        search_query = request.POST['search_query']
        # Filter your model by the search query
        posts = Article.objects.filter(
            Q(title__icontains=search_query)
            | Q(excerpt__icontains=search_query)
            | Q(author__username__icontains=search_query)
            | Q(category__title__icontains=search_query)
            | Q(description__icontains=search_query)
        )
        return render(request, 'blog/search.html', {'query':search_query, 'posts':posts})
    else:
        return render(request, 'blog/search.html',{})


class ContactFormView(FormView):
    template_name = 'blog/contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('blog:contact')
    success_message = 'پیام شما با موفیت ارسال شد.'

    def form_valid(self, form):
        current_site = get_current_site(self.request)

        mail_subject = form.cleaned_data.get('email')
        message = form.cleaned_data.get('message')
        to_email = "sina.raeisi1382@gmail.com"
        email = EmailMessage(
        mail_subject, message, to=[to_email]
        )
        email.send()
        return render(self.request, 'blog/contact_send.html')

# Create your views here.

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/base-new.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% block title %}
  	      <title>خانه</title>
  {% endblock %}
  <meta content="" name="description">
  <meta content="" name="keywords">
  <!-- Favicons -->
  <link href="{% static 'Logo/Photo_1720935200232.png' %}" rel="icon">
  <link rel="icon" type="image/png" href="{% static "Logo/Photo_1720935200232.png" %}">

  <!-- Google Fonts -->
    <link rel="stylesheet" href="{% static 'singup/assets/css/font.css' %}">
  <!-- Vendor CSS Files -->
  <link href="{% static 'singup/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'singup/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

  <!-- Template Main CSS File -->
  <link href="{% static 'singup/assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Moderna
  * Updated: May 30 2023 with Bootstrap v5.3.0
  * Template URL: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">
        
      <div class="logo">
        <h1 class="text-light" ><a href="{% url 'blog:home' %}">
            <img src="{% static "Logo/Photo_1720935200232.png" %}"  class="d-inline-block align-top" alt="web log">
        </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>
        {% block sidebar %}

        {% endblock %}
      <nav id="navbar" class="navbar">
        <ul>          
          <li><a href="{% url 'blog:home' %}">خانه</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'account:create' %}">پست جدید +</a></li>
            <li class="dropdown"><a href="#">{{ user.username }} <span><i class="bi bi-chevron-down"></i></span></a>
              <ul>
                <li><a href="{% url 'account:admin-home' %}">پروفایل</a></li>
                <li><a href="{% url 'account:password_change' %}">تغییر رمز عبور</a></li>
                <li><a href="#">بازیابی رمز عبور</a></li>
                 <form action="{% url 'account:logout' %}" method="post" class="dropdown">
                    {% csrf_token %}
                    <button type="submit">خروج</button>
                 </form>
              </ul>
            </li>
          {% else %}
            <li class="dropdown"><a href="#">User <span><i class="bi bi-chevron-down"></i></span></a>
              <ul>
                <li><a href="{% url 'account:login' %}">ورود</a></li>
                <li><a href="{% url 'account:register' %}">ثبت نام</a></li>
              </ul>
            </li>            
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
        {% block custome-header %}
        	
        {% endblock %}
    </div>
  </header><!-- End Header -->

  <main id="main">

        {% block main %}
        	
        {% endblock %}

  </main><!-- End #main -->

{% block footer %}
	
{% endblock %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'singup/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'singup/assets/vendor/php-email-form/validate.js' %}"></script>
  <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

  
  <!-- Template Main JS File -->
  <script src="{% static 'singup/assets/js/main.js' %}"></script>

</body>

</html>

templates/blog/contact.html
{% extends 'blog/base-new.html' %}

{% load crispy_forms_tags %}

{% block title %}
	<title>ارتباط با ما</title>
{% endblock %}

{% block main %}
	    <div class="container">
        <div class="col-6">
            <h1>فرم ارتباط با ما</h1>
            <h2>{{ error }}</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.email|as_crispy_field  }}
                {{ form.message|as_crispy_field  }}
                <br>
                <input type="submit" class="btn btn-success" value="ارسال">
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/contact_send.html
{% extends 'blog/base-new.html' %}

{% block title %}
	<title>عملیات با موفقیت انجام شد!</title>
{% endblock %}

{% block main %}
    <div class="col-md-8 text-center mx-auto">
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title mb-0 float-left">پیام ارسال شد</h3>
            </div>
            <div class="card-body py-4">
                <form method="post">
                    <p class="py-2">ایمیل با موفقیت ارسال شد</p>
                    <p class="py-2">جواب شما به صورت ایمیل در اسرع وقت ارسال خواهد شد</p>
                    <p class="py-2">اگر پیام مشاهده نشد حتما بخش هرزنامه ایمیل خود را نیز چک کنید</p>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
	
{% endblock %}

templates/blog/home.html
{% extends 'blog/list.html' %}

{% block header %}
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:home'  page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base-new.html' %}
{% load static %}
{% load comment_tags %}
{% load ratings %}

{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock sidebar %}
    {% block main %}

     <!-- ======= Blog Section ======= -->
     <section class="breadcrumbs">
        <div class="container">

          <div class="d-flex justify-content-between align-items-center">
            <h2>وبلاگ من</h2>

            <ol>
              <li><a href="{% url 'blog:home' %}">خانه</a></li>
            </ol>
          </div>

        </div>
      </section><!-- End Blog Section -->


                <!-- ======= Blog Section ======= -->
        {% block header %}

        {% endblock %}

      <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
          <div class="row">
            <div class="col-lg-8 entries">
                    {% for article in object_list %}
                    <article class="entry">
                    <div class="entry-img">
                      <img src="{{ article.photo.url }}" alt="" class="img-fluid">
                    </div>

                    <h2 class="entry-title" dir="rtl">
                      <a href="{% url 'blog:article-detail' article.slug  %}">
                          {{ article.title }}
                      </a>

                    </h2>

                    <div class="entry-meta">
                      <ul>
                        <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' article.author %}"> {{ article.author.get_full_name }}</a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="{% url 'blog:article-detail' article.slug  %}"><time> {{ article.jpublish }}</time></a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{% url 'blog:article-detail' article.slug  %}">{% get_comments_count article user %}</a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-eye"></i> <a href="{% url 'blog:article-detail' article.slug  %}">{{ article.hits.count }}</a></li>


                          {% if article.is_special %}
                          	 <li class="d-flex align-items-center"><i class="bi bi-star-fill"></i> <a href="#">ویژه</a></li>
                          {% endif %}
                    

                      </ul>
                    </div>


                    <div class="entry-content" dir="rtl">
                      <p>
                        {{ article.excerpt }}
                      </p>
                      <div class="read-more">
                        <a href="{% url 'blog:article-detail' article.slug  %}">بیشتر</a>
                      </div>
                        <div>
                            {% ratings article %}
                        </div>
                    </div>
                        {% for cat in article.category.active %}
                            <a href="{% url 'blog:category' cat.slug %}">#{{ cat.title }}</a>
                        {% endfor %}
                  </article><!-- End blog entry -->
                {% endfor %}
            
            <nav aria-label="Page navigation example">
              {% if is_paginated %}
              <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                  <a class="page-link" href="?page={{page_obj.previous_page_number}}"
                    >&laquo;</a
                  >
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link" href="#">&laquo;</a>
                </li>
                {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i %}
                <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endif %} {% endfor %} {% if page_obj.has_next %}
                <li class="page-item">
                  <a href="?page={{page_obj.next_page_number}}" class="page-link"
                    >&raquo;</a
                  >
                </li>
                {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&raquo;</a>
                </li>
                {% endif %}
              </ul>
              {% endif %}
            </nav>
            </div><!-- End blog entries list -->
        </div>
{% endblock %}

{% block footer %}
	  <!-- ======= Footer ======= -->
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'blog:home' %}">خانه</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">فادو</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'blog:contact' %}">ارتباط با ما</a></li>
            </ul>
          </div>
            

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Moderna</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Moderna</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/free-bootstrap-template-corporate-moderna/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->
{% endblock %}

templates/blog/sidebar.html
{% load static %}
{% load jformat %}
{% load tags %}

<div class="navbar">
    <div class="navbar-item form">
      <form style="margin-left: 20px" action="{% url 'blog:search-view' %}" method="POST" > {% csrf_token %}
        <input type="search" placeholder="جستجو..." name="search_query" required aria-label="Search">
        <button type="submit"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End sidebar search formn-->
  </div><!-- End sidebar -->

<div class="navbar">
    {% category_navbar %}
</div>